version: '3.3'
services:
  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    restart: always
  backend:
    restart: always
    build:
      context: .
    ports:
      - 3000:3000
    command: ['pnpm', 'start:prod']
    volumes:
      - './storage:/app/files'
    env_file: '.env'
