version: '3.3'
services:
  backend:
    restart: always
    build:
      context: .
    ports:
      - 3000:3000
    command: ['pnpm', 'start']
    volumes:
      - './storage:/app/files'
    env_file: '.env'
