name: Continuous Integration
on: push
jobs:
  check:
    name: Check Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.0.0'
      - name: Install Dependencies
        run: |
          apt update
          apt install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
