name: Continuous Integration
on: push
jobs:
  check:
    name: Check Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.6.1'
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint
